# Generated by Django 3.1.6 on 2021-03-13 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='hold_cost',
            new_name='holding_cost',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='prod_cost',
            new_name='production_cost',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='prod_quantity',
            new_name='production_quantity',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='prod_rate',
            new_name='production_rate',
        ),
    ]
