# Generated by Django 3.1.6 on 2021-03-13 14:42

from django.db import migrations, models
import goods.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210313_0814'),
        ('goods', '0003_auto_20210313_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='total_demand',
            field=models.FloatField(help_text='units/year', null=True, validators=[goods.models.validate_positive]),
        ),
        migrations.AlterUniqueTogether(
            name='amount',
            unique_together={('goods', 'raw_material')},
        ),
    ]
