# Generated by Django 3.1.6 on 2021-03-13 15:24

from django.db import migrations, models
import goods.models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20210313_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amount',
            name='required_amount',
            field=models.FloatField(null=True, validators=[goods.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='goods',
            name='total_demand',
            field=models.FloatField(default=1, help_text='units/year', validators=[goods.models.validate_positive]),
            preserve_default=False,
        ),
    ]
