# Generated by Django 3.1.6 on 2021-03-14 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0006_auto_20210314_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='amount',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amount', to=settings.AUTH_USER_MODEL),
        ),
    ]
