# Generated by Django 3.1.3 on 2021-03-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_amount_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='epq',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
