# Generated by Django 3.1.3 on 2021-03-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_goods_epq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='epq',
            field=models.FloatField(blank=True),
        ),
    ]
