# Generated by Django 3.1.3 on 2021-03-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_auto_20210315_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='epq',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
