# Generated by Django 3.1.6 on 2021-03-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210304_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='average_daily_demand',
            field=models.DecimalField(decimal_places=3, default='0', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='standard_deviation',
            field=models.DecimalField(blank=True, decimal_places=3, default='5', max_digits=6, null=True),
        ),
    ]
